### ISSUE TITLE
dist.barrier() hangs

### ISSUE THREAD

**Issue by liwenju0** [serend1p1ty/core-pytorch-utils#6]
i want to use cpu to train a model on two machines with two gpus on each machine. but i have encounter a confused problem.
all processes hangs on dist.barrier() call in distributed.py file。
![image](https://user-images.githubusercontent.com/16049564/227138269-0aa0856a-c721-4df3-b5c3-a5089958bb2a.png)
i have print some information to help judge. after print out "finish init_process_group, going to exec barrier", all 4 processes hangs.
then, i tried to remove dist.barrier()， it seems all right。could you give me some advice, how to debug this problem.

**Comment by liwenju0** [comment]
my command to  kick off the training is :
python -m torch.distributed.launch --nproc_per_node 2 \
    --master_port 49929 \
    --nnodes=2 --node_rank=1 \
    --master_addr=172.20.1.7 \
    --use_env train_gector_dist.py --config config.yaml


python -m torch.distributed.launch --nproc_per_node 2 \
    --master_port 49929 \
    --nnodes=2 --node_rank=0 \
    --master_addr=172.20.1.7 \
    --use_env train_gector_dist.py --config config.yaml

and the print information just as belows:

![image](https://user-images.githubusercontent.com/16049564/227166264-fa9df518-9f66-4510-97c7-478e5856905f.png)

![image](https://user-images.githubusercontent.com/16049564/227166349-516cff71-020f-438a-83f1-f412327b8b14.png)

**Comment by liwenju0** [comment]
> These distributed training related code is copyed from: https://github.com/pytorch/vision/blob/2f40a483d73018ae6e1488a484c5927f2b309969/references/detection/utils.py#L302 This should not be a code issue. Could you provice a minimal python script to reproduce the problem?

after a long day debug， i have resolved this problem. the solution is add this code in train script:
os.environ['NCCL_SOCKET_IFNAME'] = 'enp0s31f6'
os.environ["GLOO_SOCKET_IFNAME"] = 'enp0s31f6'

![image](https://user-images.githubusercontent.com/16049564/227820944-879e0a54-eb61-47b1-8091-8acd70e50502.png)

enp0s31f6  gotted from ifconfig output:
![image](https://user-images.githubusercontent.com/16049564/227821030-e1896adb-bcad-48e4-8122-68714d5f19cb.png)

i think many ifname make the nccl confused with select right one

**Comment by serend1p1ty** [comment]
Strange bug...

**Comment by serend1p1ty** [comment]
@liwenju0 I have the same problem as you.
In order not to modify the code, I use `export NCCL_SOCKET_IFNAME=$ifname`。
It seems that there is something wrong with the network port of my machine. Because `ifconfig` displays fewer network ports than before.
